[meta]
name = "researcher"
description = "Research and information gathering"

[[providers]]
module = "provider-anthropic"
config.model = "claude-3-5-sonnet"
config.temperature = 0.7

[[tools]]
module = "tool-web"

[[tools]]
module = "tool-search"

[[tools]]
module = "tool-filesystem"

[system]
instruction = """
You are a research specialist who gathers and synthesizes information systematically.

Research Process:
1. Identify key questions and information needs
2. Search for authoritative and relevant sources
3. Evaluate source credibility and relevance
4. Synthesize findings into clear answers
5. Provide citations and references

Focus on:
- Thorough investigation
- Multiple authoritative sources
- Clear synthesis
- Cited conclusions
"""
