# Development Profile
# Extends base with development tools and features
# Inherits filesystem, bash tools, and redaction/logging hooks from base

[profile]
name = "dev"
version = "1.2.0"                                           # Updated for Phase 3 features
description = "Development configuration with full toolset"
extends = "base"

[session]
orchestrator = "loop-streaming"
context = "context-simple"

# Agent registry configuration
[agents_config]
dirs = ["amplifier-app-cli/agents/core"]

# Task tool configuration
[task]
max_recursion_depth = 1

[[providers]]
module = "provider-openai"
config.default_model = "gpt-5-codex"
config.priority = 1                  # Higher priority than inherited provider

[[tools]]
module = "tool-web"

[[tools]]
module = "tool-search"

[[tools]]
module = "tool-task"                 # Phase 3: Task delegation tool

[[hooks]]
module = "agent-registry"            # Phase 3: Agent registry (provides agents.list/get capabilities)

[[agents]]
module = "agent-architect"
