# Development Profile
# Extends base with development tools and features
# Inherits filesystem, bash tools, and redaction/logging hooks from base

[profile]
name = "dev"
version = "1.2.0"                                           # Updated for Phase 3 features
description = "Development configuration with full toolset"
extends = "base"

[session]
orchestrator = "loop-streaming"
context = "context-simple"

[orchestrator.config]
extended_thinking = true  # Enable thinking blocks for Claude Sonnet 4.5

# Task tool configuration
[task]
max_recursion_depth = 1

# UI display configuration (Phase 4)
[ui]
show_thinking_stream = true
show_tool_lines = 5

# Use Anthropic provider from foundation (supports extended_thinking and tools)
# No provider override - inherits provider-anthropic with claude-sonnet-4-5

[[tools]]
module = "tool-web"

[[tools]]
module = "tool-search"

[[tools]]
module = "tool-task"                 # Phase 3: Task delegation tool

[[hooks]]
module = "hooks-streaming-ui"        # Streaming UI display for thinking and tools

# Agent configurations (config overlays for sub-session spawning)
[agents.zen-architect]
description = "System design with ruthless simplicity"
[[agents.zen-architect.providers]]
module = "provider-anthropic"
config.model = "claude-3-5-sonnet"
config.temperature = 0.7
[[agents.zen-architect.tools]]
module = "tool-filesystem"
[[agents.zen-architect.tools]]
module = "tool-bash"
[agents.zen-architect.system]
instruction = "You are a zen architect who values ruthless simplicity. Question every abstraction, favor clarity over cleverness."

[agents.bug-hunter]
description = "Systematic debugging and bug fixing"
[[agents.bug-hunter.providers]]
module = "provider-anthropic"
config.model = "claude-3-5-sonnet"
config.temperature = 0.3
[[agents.bug-hunter.tools]]
module = "tool-filesystem"
[[agents.bug-hunter.tools]]
module = "tool-bash"
[agents.bug-hunter.system]
instruction = "You are a systematic debugger. Form hypotheses, test methodically, isolate root causes, propose minimal fixes."

[agents.researcher]
description = "Research and information gathering"
[[agents.researcher.providers]]
module = "provider-anthropic"
config.model = "claude-3-5-sonnet"
[[agents.researcher.tools]]
module = "tool-web"
[[agents.researcher.tools]]
module = "tool-search"
[[agents.researcher.tools]]
module = "tool-filesystem"
[agents.researcher.system]
instruction = "You are a research specialist. Identify key questions, search authoritative sources, synthesize findings with citations."
