# Development Profile
# Extends base with development tools and features
# Inherits filesystem, bash tools, and redaction/logging hooks from base

[profile]
name = "dev"
version = "1.1.0"  # Updated to reflect base changes
description = "Development configuration with full toolset"
extends = "base"

[session]
orchestrator = "loop-streaming"
context = "context-simple"

[[tools]]
module = "tool-web"

[[tools]]
module = "tool-search"

[[agents]]
module = "agent-architect"
