[profile]
name = "experimental"
version = "1.0.0"
description = "Experimental profile with aggressive settings"
extends = "dev"

[session]
orchestrator = "loop-streaming"
context = "context-persistent"
max_tokens = 200000

[context]
files = [
    "./docs/guidance/principles.md",
    "./docs/guidance/*-every-turn.md",
    "./docs/research/*.md"
]
# No limit on recursion depth

[agents]
dirs = ["./agents/core", "./agents/experimental", "./agents/research"]

[task]
max_recursion_depth = 3

[ui]
show_tool_lines = 10