# Foundation Profile
# Absolute minimum configuration - just orchestrator, context, and provider
# This profile serves as the base for all other profiles

[profile]
name = "foundation"
version = "1.0.0"
description = "Foundation configuration with only essential components"

[session]
orchestrator = "loop-basic"
context = "context-simple"

[[providers]]
module = "provider-anthropic"
config.default_model = "claude-sonnet-4-5"
