# Minimal Profile
# Absolute minimum for running Amplifier

[profile]
name = "minimal"
version = "1.0.0"
description = "Minimal configuration with only essential components"

[session]
orchestrator = "loop-basic"
context = "context-simple"

[[providers]]
module = "provider-anthropic"
